import Header from '../components/Header';
import Footer from '../components/Footer';
import Head from 'next/head';

export const metadata = {
  title: 'Solana-market',
  description: 'Generated by Next.js',
};

export default function RootLayout({children,}: {children: React.ReactNode;}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="author" content="themesflat.com" />
        <link rel="stylesheet" href="/assets/css/style.css" />
        <link rel="stylesheet" href="/assets/css/responsive.css" />
        <link rel="shortcut icon" href="/assets/icon/Favicon.png" />
        <link rel="apple-touch-icon-precomposed" href="/assets/icon/Favicon.png" />

      </head>
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
